[package]
name = "mcp4728-examples"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
fugit = "0.3.6"
mcp4728 = { path = ".." }
panic-halt = "1.0.0"
rp-pico = "0.9.0"
rp2040-hal = "0.10.0"

[[bin]]
name = "pi_pico"
